name: Release Lawnchairmodule

on:
  push:
    branches:
      - main  # Adjust this according to your default branch

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Prepare Lawnchairmodule Artifact (Exclude priv-app2)
        uses: ./prepare-artifact.sh  # This script will be defined later
        with:
          artifact_name: Lawnchairmodule
          excluded_folder: system/priv-app2

      - name: Upload Lawnchairmodule Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.prepare-artifact.outputs.artifact_path }}  # Use output from script
          path: ${{ steps.prepare-artifact.outputs.artifact_path }}

      - name: Prepare Lawnchairmodule2 Artifact (Exclude priv-app, Rename priv-app2)
        uses: ./prepare-artifact.sh  # Reuse the script
        with:
          artifact_name: Lawnchairmodule2
          excluded_folder: system/priv-app
          rename_folder: system/priv-app2:system/priv-app

      - name: Upload Lawnchairmodule2 Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.prepare-artifact.outputs.artifact_path }}  # Use output from script
          path: ${{ steps.prepare-artifact.outputs.artifact_path }}

      - name: Remove .github and .git folders (Optional)
        run: |
          find . -type d -name .github -exec rm -rf {} +
          rm -rf .git  # Only uncomment if necessary
