name: Release Lawnchairmodule
on:
  push:
    branches:
              - develop
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Create artifact for Lawnchair14_New_Accent
      uses: actions/upload-artifact@v3
      with:
        name: Lawnchair14_New_Accent
        path: Lawnchair14_New_Accent/

    - name: Create artifact for Lawnchair14_Old_A12_Accent
      uses: actions/upload-artifact@v3
      with:
        name: Lawnchair14_Old_Accent
        path: Lawnchair14_Old_A12_Accent/
