name: Release

on:
  workflow_dispatch:

permissions:
  contents: write  # Ensure the GITHUB_TOKEN has the correct permissions

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Remove .github and .git folders
      run: |
        find . -type d -name .github -exec rm -rf {} +
        rm -rf .git

    # First artifact: Lawnchairmodule
    - name: Prepare Lawnchairmodule
      run: |
        mkdir -p artifact1
        rsync -av --progress ./ artifact1 --exclude .github --exclude .git --exclude system/priv-app2
      shell: bash

    - name: Zip Lawnchairmodule
      run: zip -r Lawnchairmodule.zip artifact1

    # Second artifact: Lawnchairmodule2
    - name: Prepare Lawnchairmodule2
      run: |
        mkdir -p artifact2
        rsync -av --progress ./ artifact2 --exclude .github --exclude .git --exclude system/priv-app
        mv artifact2/system/priv-app2 artifact2/system/priv-app
      shell: bash

    - name: Zip Lawnchairmodule2
      run: zip -r Lawnchairmodule2.zip artifact2

    - name: Read Changelog
      id: changelog
      run: echo "changelog=$(cat changelog.md)" >> $GITHUB_ENV

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.event.release.tag_name }}
        release_name: ${{ github.event.release.name }}
        body: ${{ env.changelog }}
        draft: false
        prerelease: false

    - name: Upload Lawnchairmodule to Release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: Lawnchairmodule.zip
        asset_name: Lawnchairmodule.zip
        tag: ${{ github.event.release.tag_name }}

    - name: Upload Lawnchairmodule2 to Release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: Lawnchairmodule2.zip
        asset_name: Lawnchairmodule2.zip
        tag: ${{ github.event.release.tag_name }}
