name: Release

on:
  push:
    branches:
    - main

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Lawnchairmodule (replace with your build commands)
      run: |
        # Add your build commands here
        # Example: ./gradlew assembleRelease

    - name: Prepare Lawnchairmodule
      run: |
        mkdir -p artifact1
        rsync -av --progress ./ artifact1 --exclude .github --exclude .git --exclude system/priv-app2

    - name: Upload Lawnchairmodule
      uses: actions/upload-artifact@v4
      with:
        name: Lawnchairmodule
        path: artifact1

    - name: Prepare Lawnchairmodule2
      run: |
        mkdir -p artifact2
        rsync -av --progress ./ artifact2 --exclude .github --exclude .git --exclude system/priv-app
        mv artifact2/system/priv-app2 artifact2/system/priv-app

    - name: Upload Lawnchairmodule2
      uses: actions/upload-artifact@v4
      with:
        name: Lawnchairmodule2
        path: artifact2

  publish-release:
    runs-on: ubuntu-latest
    needs: build-and-upload
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Download artifacts
      uses: actions/download-artifact@v4  # Remove duplicate download step
      with:
        name: Lawnchairmodule  # Separate artifact names
        path: artifacts1

    - name: Download artifacts
      uses: actions/download-artifact@v4  # Remove duplicate download step
      with:
        name: Lawnchairmodule2  # Separate artifact names
        path: artifacts2

    - name: Publish GitHub release
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use a secret for access token
      with:
        tag_name: v5.0
        release: ${{ github.event.inputs.release }}
        draft: false
        body_path: ${{ github.workspace }}/changelog.md  # Replace with changelog location
        files: artifacts/*.zip
        name: ${{ github.event.inputs.releaseName }}
