name: Release
 
on:
  workflow_dispatch:
    inputs:
      RELEASE_TAG:
        description: 'Tag for the Release'
        required: true

jobs:
  publish-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Make Lawnchair Module
        run: zip -r Lawnchair.zip * -x .git* -x ./system/priv-app2

      - name: Make Lawnchair Mod Module
        run: |
            rm -rf ./system/priv-app
            mv ./system/priv-app2 ./system/priv-app
            zip -r Lawnchair-Mod.zip * -x .git* Lawnchair.zip

      - name: Publish GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.RELEASE_TAG }}
          name: Lawnchair ${{ github.event.inputs.RELEASE_TAG }}
          draft: false
          body_path: ${{ github.workspace }}/changelog.md
          files: |
            Lawnchair.zip
            Lawnchair-Mod.zip
