name: Release
 
on:
  workflow_dispatch:
    inputs:
      RELEASE_TAG:
        description: 'Tag for the Release'
        required: true

jobs:
  publish-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Make Lawnchair Module
        run: |
            mkdir Lawnchair
            mv * Lawnchair/
            mv -r Lawnchair/system/priv-app2 ./
            cd Lawnchair
            zip -r Lawnchair.zip * -x .git*
            mv Lawnchair.zip ../
            cd ${{ github.workspace }}

      - name: Make Lawnchair Mod Module
        run: |
            mv Lawnchair Lawnchair-Mod
            rm -r Lawnchair-Mod/system/priv-app
            mv ./priv-app2 Lawnchair-Mod/system/priv-app
            cd Lawnchair-Mod
            zip -r Lawnchair-Mod.zip * -x .git*
            mv Lawnchair-Mod.zip ../
            cd ${{ github.workspace }}

      - name: Publish GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.RELEASE_TAG }}
          name: Lawnchair ${{ github.event.inputs.RELEASE_TAG }}
          draft: false
          body_path: ${{ github.workspace }}/changelog.md
          files: |
            Lawnchair.zip
            Lawnchair-Mod.zip
