name: Release

on:
  push:
    branches:
    - main

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Lawnchairmodule (replace with your build commands)
      run: |
        # Add your build commands here
        # Example: ./gradlew assembleRelease

    - name: Prepare Lawnchairmodule
      run: |
        mkdir -p artifact1
        rsync -av --progress ./ artifact1 --exclude .github --exclude .git --exclude system/priv-app2

    - name: Upload Lawnchairmodule
      uses: actions/upload-artifact@v4
      with:
        name: Lawnchairmodule
        path: artifact1

    - name: Prepare Lawnchairmodule2
      run: |
        mkdir -p artifact2
        rsync -av --progress ./ artifact2 --exclude .github --exclude .git --exclude system/priv-app
        mv artifact2/system/priv-app2 artifact2/system/priv-app

    - name: Upload Lawnchairmodule2
      uses: actions/upload-artifact@v4
      with:
        name: Lawnchairmodule2
        path: artifact2

  publish-release:
    runs-on: ubuntu-latest
    needs: build-and-upload
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Download artifacts1
      uses: actions/download-artifact@v4
      with:
        name: Lawnchairmodule
        path: artifacts1

    - name: Download artifacts2
      uses: actions/download-artifact@v4
      with:
        name: Lawnchairmodule2
        path: artifacts2

    - name: Get latest tag
      id: get_tag
      run: echo ::set-output name=TAG_NAME::$(git describe --abbrev=0 --tags)

    - name: Extract current tag version
      id: extract_tag_version
      run: echo ::set-output name=TAG_VERSION::${{ steps.get_tag.outputs.TAG_NAME | split('-')[0] }}

    - name: Increment tag version
      id: increment_tag_version
      run: echo ::set-output name=NEW_TAG_VERSION::$((${{ steps.extract_tag_version.outputs.TAG_VERSION }} + 1))

    - name: Publish GitHub release
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.increment_tag_version.outputs.NEW_TAG_VERSION }}.0
        release: ${{ github.event.inputs.release }}
        draft: false
        body_path: ${{ github.workspace }}/changelog.md
        files: artifacts1/* artifacts2/*
        name: ${{ github.event.inputs.releaseName }}
