name: Release
 
on:
  workflow_dispatch:
    inputs:
      RELEASE_NAME:
        description: 'Name for the release'
        required: true
      RELEASE_TAG:
        description: 'Tag for the Release'
        required: true

jobs:
  publish-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Make Lawnchair Module
        run: |
            zip -r Lawnchair.zip * -x .git* ./system/priv-app2
        id: lawnchair-zip

      - name: Make Lawnchair Mod Module
        run: |
            rm -rf ./system/priv-app
            mv ./system/priv-app2 ./system/priv-app
            zip -r Lawnchair-Mod.zip * -x .git*
        id: lawnchair2-zip

      - name: Publish GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.RELEASE_TAG }}
          name: ${{ github.event.inputs.RELEASE_NAME }}
          draft: false
          body_path: ${{ github.workspace }}/changelog.md
          files: |
            Lawnchair.zip
            Lawnchair-Mod.zip
