name: Release Lawnchair

on:
  workflow_dispatch:

permissions:
  contents: write
jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Get current version tag
      id: get_version
      run: |
        git fetch --tags
        if [ $(git tag -l "v*" | wc -l) -eq 0 ]; then
          echo "version=v1.0" >> $GITHUB_ENV
        else
          latest_tag=$(git tag -l "v*" | sort -V | tail -n 1)
          version_number=$(echo $latest_tag | cut -d'.' -f1 | cut -c2-)
          new_version_number=$((version_number + 1))
          new_version="v${new_version_number}.0"
          echo "version=${new_version}" >> $GITHUB_ENV
        fi

    - name: Create new version tag
      run: |
        git tag ${{ env.version }}
        git push origin ${{ env.version }}

    - name: Zip Lawnchair14_New_Accent
      run: zip -r Lawnchair14_New_Accent.zip Lawnchair14_New_Accent

    - name: Zip Lawnchair14_Old_Accent
      run: zip -r Lawnchair14_Old_Accent.zip Lawnchair14_Old_A12_Accent

    - name: Create GitHub release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.version }}
        release_name: Lawnchair 14 ${{ env.version }}
        body_path: changelog.md
        draft: false
        prerelease: false

    - name: Upload Lawnchair14_New_Accent to release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./Lawnchair14_New_Accent.zip
        asset_name: Lawnchair14_New_Accent.zip
        asset_content_type: application/zip

    - name: Upload Lawnchair14_Old_Accent to release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./Lawnchair14_Old_Accent.zip
        asset_name: Lawnchair14_Old_Accent.zip
        asset_content_type: application/zip